package com.healthcare.models;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Clinical notes entered by the doctor after the visit.
 * Triggers the LLM post-visit patient-friendly summary (async).
 */
@Entity
@Table(name = "visit_notes")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class VisitNote {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /** One-to-one with Appointment */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "appointment_id", nullable = false, unique = true)
    private Appointment appointment;

    /** Raw clinical notes written by the doctor */
    @Column(name = "clinical_notes", nullable = false, columnDefinition = "TEXT")
    private String clinicalNotes;

    /** Patient-friendly summary generated by LLM (null if llm_status != SUCCESS) */
    @Column(name = "patient_summary", columnDefinition = "TEXT")
    private String patientSummary;

    @Enumerated(EnumType.STRING)
    @Column(name = "llm_status", nullable = false)
    private LlmStatus llmStatus;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /** One visit note → many prescription lines */
    @OneToMany(mappedBy = "visitNote", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Prescription> prescriptions;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        if (llmStatus == null) llmStatus = LlmStatus.PENDING;
    }

    public enum LlmStatus { PENDING, SUCCESS, FAILED }
}
